### PR TITLE
Created a getBranches query that returns the branches that belong to …

### PR DESCRIPTION
**Pull request by eenwemasor**
Created a getCompanyBranches query that returns the branches that belong to the company

### CODE REVIEW

**Review by omadoyeabraham — CHANGES_REQUESTED** [review]
@enwemasor1995 While what you have done is technically correct, it's overkill for a task that is simple to accomplish. Please do the following:

1. In `UserProfile.graphql` add an @hasMany relationship for the branches, like this:
```
type Company {
    id: ID!
    name: String!
    location: String
    branches: [CompanyBranch]! @hasMany
}
```

2. Create a `companies.graphql` query file, and add the following query.
```
    """ Get a company by their ID """
    GetCompanyById(id: ID! @eq): Company  @find(model: "App\\Models\\Company")
```

That's all, you can then query to get a company, and by getting the company also get its branches.

@davidubanyi @enwemasor1995 We need to begin to think of our data in terms of graphs of related data types, so we can properly utilise the advantages that GraphQL provides. This way we don't end up creating multiple queries that can be gotten from a single parent query.

Also @enwemasor1995 Ensure that you add tests for this query. Thanks

**Comment by eenwemasor** [comment]
@davidubanyi  mentioned not requiring ID to query the branches

**Comment by omadoyeabraham** [comment]
@enwemasor1995 In that case use the @first directive from the lighthouse php package. Create a query called GetCompany. Since there will be only one company in the DB, you can get the first company instead of getting by ID

**Comment by eenwemasor** [comment]
created a new branch for the correct #77

**Pull request closed without merging**
