### PR TITLE
Feature/50/customer withdrawal request

### PR DESCRIPTION
**Pull request by Oluwablin**
created enhancement for customer withdrawal requests

### CODE REVIEW

**Comment by omadoyeabraham** [comment]
@Oluwablin I cannot see any tests for the newly added functionality

**Comment by Oluwablin** [comment]
> @Oluwablin I cannot see any tests for the newly added functionality

@omadoyeabraham I will write the tests now. I tested them on graphql playground before pushing, though.

**Comment by Oluwablin** [comment]
> > @Oluwablin I cannot see any tests for the newly added functionality
> 
> @omadoyeabraham I will write the tests now. I tested them on graphql playground before pushing, though.

@omadoyeabraham tests completed now, please review.

**Comment by omadoyeabraham** [comment]
Closing this, as the functionality already exists

**Pull request closed without merging**
